"""add user email

Revision ID: ba1e99aa93e1
Revises: f6bee820755e
Create Date: 2024-10-02 13:12:39.940915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba1e99aa93e1'
down_revision: Union[str, None] = 'f6bee820755e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_user', sa.Column('email', sa.String(length=30), nullable=True))
    op.create_unique_constraint('uix_service_user_email', 'service_user', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_service_user_email', 'service_user', type_='unique')
    op.drop_column('service_user', 'email')
    # ### end Alembic commands ###
